# Generated by Django 2.0.4 on 2018-04-26 05:42

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rear_end_services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attack',
            fields=[
                ('attack_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('attack_type_name', models.CharField(max_length=100, verbose_name='袭击方式')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.IntegerField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=100, verbose_name='国家名')),
            ],
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('region_id', models.IntegerField(primary_key=True, serialize=False)),
                ('region_name', models.CharField(max_length=100, verbose_name='地区名')),
            ],
        ),
        migrations.CreateModel(
            name='Target',
            fields=[
                ('target_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('target_type_name', models.CharField(max_length=200, verbose_name='袭击目标')),
            ],
        ),
        migrations.CreateModel(
            name='TerrorismData',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('year', models.IntegerField(blank=True, verbose_name='年份')),
                ('month', models.IntegerField(blank=True, verbose_name='月份')),
                ('day', models.IntegerField(blank=True, verbose_name='日期')),
                ('date', models.DateField(blank=True, verbose_name='时间')),
                ('city', models.CharField(blank=True, max_length=200, verbose_name='城市')),
                ('summary', models.TextField(blank=True, verbose_name='事件报道')),
                ('suicide', models.IntegerField(blank=True, choices=[(0, 'no'), (1, 'yes')], verbose_name='自杀式袭击')),
                ('group_name', models.CharField(blank=True, max_length=200, verbose_name='组织名称')),
                ('motive', models.TextField(blank=True, verbose_name='动机')),
                ('num_kill', models.IntegerField(blank=True, verbose_name='死亡人数')),
                ('num_wound', models.IntegerField(blank=True, verbose_name='受伤人数')),
                ('prop_value', models.FloatField(blank=True, verbose_name='经济损失')),
                ('prop_comment', models.TextField(blank=True, verbose_name='损失情况')),
                ('attack_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rear_end_services.Attack', verbose_name='袭击方式')),
                ('country_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rear_end_services.Country', verbose_name='国家')),
                ('region_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rear_end_services.Region', verbose_name='地区')),
                ('target_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rear_end_services.Target', verbose_name='袭击目标')),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('weapon_type_id', models.IntegerField(primary_key=True, serialize=False)),
                ('weapon_type_name', models.CharField(max_length=100, verbose_name='武器类型')),
            ],
        ),
        migrations.AlterField(
            model_name='globalterrorism',
            name='day',
            field=models.CharField(max_length=50, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='globalterrorism',
            name='geom',
            field=django.contrib.gis.db.models.fields.PointField(srid=4326, verbose_name='位置'),
        ),
        migrations.AlterField(
            model_name='globalterrorism',
            name='month',
            field=models.CharField(max_length=50, verbose_name='月份'),
        ),
        migrations.AlterField(
            model_name='globalterrorism',
            name='year',
            field=models.CharField(max_length=50, verbose_name='年份'),
        ),
        migrations.AddField(
            model_name='terrorismdata',
            name='weapon_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rear_end_services.Weapon', verbose_name='武器类型'),
        ),
    ]
