# Generated by Django 2.0.4 on 2018-04-26 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rear_end_services', '0002_auto_20180426_1342'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrorismdata',
            name='day',
            field=models.IntegerField(blank=True, db_index=True, verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='terrorismdata',
            name='month',
            field=models.IntegerField(blank=True, db_index=True, verbose_name='月份'),
        ),
        migrations.AlterField(
            model_name='terrorismdata',
            name='suicide',
            field=models.IntegerField(blank=True, choices=[(0, 'no'), (1, 'yes')], db_index=True, verbose_name='自杀式袭击'),
        ),
        migrations.AlterField(
            model_name='terrorismdata',
            name='year',
            field=models.IntegerField(blank=True, db_index=True, verbose_name='年份'),
        ),
    ]
