# Generated by Django 2.0.4 on 2018-05-09 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rear_end_services', '0002_auto_20180509_2354'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='region_name',
            field=models.CharField(max_length=100, null=True, verbose_name='地区名'),
        ),
    ]
