# Generated by Django 2.0.4 on 2018-05-15 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rear_end_services', '0003_auto_20180510_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='keyword',
            name='word',
            field=models.CharField(db_index=True, max_length=50, verbose_name='关键词'),
        ),
    ]
