# Generated by Django 2.0.4 on 2018-04-26 11:56

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rear_end_services', '0004_auto_20180426_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrorismdata',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(null=True, srid=4326, verbose_name='位置'),
        ),
    ]
