# Generated by Django 2.0.4 on 2018-05-09 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rear_end_services', '0004_auto_20180510_0008'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='region_name',
        ),
        migrations.RemoveField(
            model_name='country',
            name='rid',
        ),
    ]
