# Generated by Django 2.0.4 on 2018-05-10 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rear_end_services', '0005_country_region'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='rid',
        ),
    ]
