# Generated by Django 2.0.4 on 2018-05-05 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rear_end_services', '0005_terrorismdata_location'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GlobalTerrorism',
        ),
        migrations.DeleteModel(
            name='WorldBorder',
        ),
    ]
