# Generated by Django 2.0.4 on 2018-05-08 16:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rear_end_services', '0006_auto_20180506_0045'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrorismdata',
            name='attack_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attack', to='rear_end_services.Attack', verbose_name='袭击方式'),
        ),
        migrations.AlterField(
            model_name='terrorismdata',
            name='country_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='country', to='rear_end_services.Country', verbose_name='国家'),
        ),
        migrations.AlterField(
            model_name='terrorismdata',
            name='region_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='region', to='rear_end_services.Region', verbose_name='地区'),
        ),
        migrations.AlterField(
            model_name='terrorismdata',
            name='target_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='target', to='rear_end_services.Target', verbose_name='袭击目标'),
        ),
        migrations.AlterField(
            model_name='terrorismdata',
            name='weapon_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='weapon', to='rear_end_services.Weapon', verbose_name='武器类型'),
        ),
    ]
